CruGlobal/conf-registration-web

app/scripts/services/AnswerCache.js
@OzzieOrca Can you review this?  This will remove the unneeded PUTs to the answers endpoint when a registration page is loaded.
=> Only update answers when needed

app/css/style.less, app/scripts/controllers/eventRegistrations.js, app/views/eventRegistrations.html
@adammeyer Please review our changes and do the merge.  Thanks!  -Jay
=> Adding registrant withdrawn feature

app/scripts/directives/pickadate.js, app/views/blocks/dateQuestion.html, bower.json
disabled attribute was also being applied to the year dropdown in IE. @adammeyer can you review?
=> Fix pickadate year dropdown selector from being disabled in IE

app/scripts/controllers/editRegistrationModal.js
Hey @adammeyer,  I just noticed you already merged EVENT-173. The version you had works fine but I was thinking about some small changes and didn't get to them till today. I made saving individual answers async and cleaned up logic and refactored duplicate code into functions.
It took me a while to figure out what this code was trying to do and I feel like this version is easier to read. Let me know what you think. It's not urgent in any way.
=> Cleanup to EVENT-173

app/scripts/directives/pickadate.js
@adammeyer can you review? When the picker is in a modal, it is confined to the modal container and isn't positioned correctly. This issue came up inside the editRegistrationModal.
=> Fix issue with pickadate when it is inside a modal

app/scripts/directives/registrationTypeSelect.js, app/views/components/registrationTypeSelect.html
@adammeyer would you take a look at this, please?  I'm just adding a quick angular thing to hide the registration amount if it's zero dollars.  Thanks.
=> Showing registration cost only when it's greater than $0.00.

app/index.html
@adammeyer Can you review and merge this? I guess I had used the non-compressed versions for debugging and never switched them
=> Use compressed .js and .css files for pickadate

app/scripts/directives/block.js, app/views/components/blockDirective.html
@adammeyer can you review? Is the best way to do this to hide the entire tab? We could also just disable the tab so it looks disabled on mouseover and isn't clickable.
https://jira.cru.org/browse/EVENT-166
=> EVENT-166: Force blocks of profile type NAME or EMAIL to be shown for all reg types

app/index.html, app/scripts/directives/autoFocus.js, app/views/modals/accessEvent.html, app/views/modals/cloneEvent.html, app/views/modals/createEvent.html, bower.json
-Auto focus text fields on modal open
-update angular-bootstrap
=> Auto focus text fields on modal open

app/scripts/controllers/paymentModal.js, app/views/eventPermissions.html
=> Restrict update permission level

app/scripts/controllers/eventRegistrations.js
@ryancarlson this is a temporary fix until we get the PUT registrant built.  Can you review?
Thanks @dsgoers for the idea!
=> GET registration before update of registrant

app/views/modals/paymentsModal.html, app/views/paymentMethods/scholarshipAdmin.html, app/views/paymentMethods/transfer.html
Added a third account type for transfer/scholarship payments.  The conferences team wanted a field that can have a longer/shorter number and/or a name and description.  For now, this is OK with them.
=> Event 411 - non us staff payments

app/scripts/controllers/eventRegistrations.js, app/scripts/controllers/paymentModal.js, app/scripts/services/PermissionCache.js, app/views/eventPermissions.html, app/views/modals/cloneEvent.html
This PR adds check in, a new permission level that is similar to update except users cannot delete registrations or update the event.
=> Event 404 - check in permission

app/scripts/controllers/eventDetails.js
URL Validation fix for https websites and for multiple regex tests
=> URL validation

app/scripts/controllers/eventRegistrations.js, app/views/eventRegistrations.html
'On the list of registrations conference admin page, Unlock "Started," "Completed" and "Email" display columns to allow admin to remove from display screen (leaving the "First Name," "Last Name," "Registrant Type" and "Paid" locked).'
=> EVENT - 428

app/index.html, app/less/components.less, app/scripts/directives/blockEditor.js, app/scripts/directives/pickadate.js, app/scripts/filters/dateRangeFormat.js, app/views/blocks/dateQuestion.html, app/views/components/blockEditor.html, app/views/components/pickadate.html
@hlbraddock , Implemented Min / MAx range for Date questions, please test.
=> Event 380 valid option range for date questions

app/less/common.less, app/less/components.less, app/scripts/directives/blockEditor.js, app/scripts/services/validateRegistrant.js, app/views/components/blockEditor.html, app/views/components/blockRegistration.html
Rules support for any match in a [subset] of dropdown or multiple choice answers or checkbox as per https://jira.cru.org/browse/EVENT-432
This branch replaces https://github.com/CruGlobal/conf-registration-web/tree/EVENT-432-Rules-support-for-any-match
This branch replaced its predecessor for the following reasons:
1. Removed reformatting
2. Simplify merge with master branch.
@jayakrishnanv @OzzieOrca
=> EVENT-432 Rules Support

app/less/common.less, app/scripts/directives/blockEditor.js, app/views/components/blockEditor.html, app/views/components/blockRegistration.html, app/views/popupHyperlinkInformation.html, app/views/reviewRegistration.html
As per https://jira.cru.org/browse/EVENT-434
This PR replaces https://github.com/CruGlobal/conf-registration-web/pull/493/files
=> EVENT-434 Allow embedded hyperlinks to link to external sites

app/index.html, app/less/common.less, app/less/components.less, app/scripts/directives/blockEditor.js, app/scripts/directives/blockRegistration.js, app/scripts/directives/pickadate.js, app/scripts/directives/showErrors.js, app/scripts/directives/stringToNumber.js, app/scripts/filters/dateRangeFormat.js, app/scripts/services/validateRegistrant.js, app/views/blocks/checkboxQuestion.html, app/views/blocks/dateQuestion.html, app/views/blocks/numberQuestion.html, app/views/blocks/radioQuestion.html, app/views/blocks/selectQuestion.html, app/views/components/blockEditor.html, app/views/components/blockRegistration.html, app/views/components/pickadate.html, app/views/popupHyperlinkInformation.html, app/views/reviewRegistration.html
@hlbraddock @jcsaplar @OzzieOrca Fresh branch for https://jira.cru.org/browse/EVENT-381, please discard the old branch #491 . Please test and merge to master if approved.
=> EVENT-381-Implemented default option

app/index.html, app/less/common.less, app/less/components.less, app/scripts/directives/blockEditor.js, app/scripts/directives/blockRegistration.js, app/scripts/directives/rule.js, app/scripts/filters/showQuestionFilter.js, app/scripts/services/constants.js, app/scripts/services/validateRegistrant.js, app/views/blocks/checkboxQuestion.html, app/views/components/blockEditor.html, app/views/components/rule.html
@hlbraddock @OzzieOrca @jcsaplar Implemented force selection based on the new `rule_type` field in `rules` table. This needs to be tested in conjunction with the back-end changes in https://github.com/CruGlobal/ert-api/pull/679
=> EVENT-436 - single rule table

app/scripts/services/validateRegistrant.js
- Add rollbar error if ruleType is ever not defined
=> Pass ruleType to blockVisibleRuleCheck in validate

app/views/help.html, app/views/privacy.html
Changed email addresses to help@cru.org from apps@cru.org
=> Event 456 set help email

app/scripts/directives/blockEditor.js, app/scripts/directives/rule.js, app/scripts/services/validateRegistrant.js
@hlbraddock, @jcsaplar @OzzieOrca  Implemented rules based on checkbox questions, as per https://jira.cru.org/browse/EVENT-461. Please review.
=> Event-461 - Implemented rules based on checkbox questions

app/index.html, app/scripts/directives/datepicker.js, app/scripts/directives/ngEnter.js, app/scripts/directives/questionToolbar.js, bower.json, karma.conf.js
Upgrade to jQuery 3.0.0 and compensate for any breaking changes.
=> Upgrade to jQuery 3

app/scripts/controllers/eventDetails.js, app/scripts/services/ConfCache.js, app/views/eventDetails/paymentOptions.html, app/views/modals/paymentsModal.html, test/spec/testData.js
Implement [EVENT-484](https://jira.cru.org/browse/EVENT-484), modifying fields and labels in the credit card payment options form. @hlbraddock please make sure that my changes match your expectations.
This PR will break things if merged into master. That is why I am requesting to merge it into the EVENT-485 branch, which can collect PRs for subtasks until this feature is completed, at which point we can merge that branch into master.
=> Modify the payment options form for TSYS

app/index.html, app/scripts/app.js, app/scripts/controllers/reviewRegistration.js, app/scripts/directives/payment.js, app/scripts/services/error.js, app/scripts/services/payment.js, bower.json
Tokenize credit card payments via TSYS using the `cru-payments` library.
=> Support payments through TSYS

app/scripts/services/ConfCache.js, app/views/eventDetails/regOptions.html
Add an option to automatically combine spouse's registrations.
=> Add combine spouse registrations option

bower.json
I meant to do this at the same time and forgot about it.
https://github.com/CruPCI/cru-payments/releases
=> Upgrade cru-payments

README.md
Doug may be working on the ERT some and I figured this would be good to document.
=> Add deployment info to readme

app/scripts/controllers/landing.js, app/scripts/directives/blockEditor.js, app/scripts/directives/blockRegistration.js, test/spec/controllers/landing.spec.js
https://jira.cru.org/browse/EVENT-506
=> EVENT-506: Refactor default answer values in blockRegistraion

app/scripts/controllers/landing.js
Decrease debounce from 1000 to 800 milliseconds.
=> EVENT-449-2

app/views/help.html, app/views/privacy.html
As per https://secure.helpscout.net/conversation/437962889/165600.
=> Change help@cru.org to support@eventregistrationtool.com

app/views/paymentMethods/creditCard.html
This PR adds expiration years to make 20 instead of 9, this matches what Amazon does.  Based on [this HS ticket](https://secure.helpscout.net/conversation/491743860/185610?folderId=320670).
=> HS-185610 - Extend CC Expiration Years

app/scripts/directives/blockEditor.js, app/scripts/directives/blocks.js, app/scripts/directives/questionToolbar.js, app/views/blocks/campusQuestion.html, app/views/components/blockEditor.html, app/views/components/blockRegistration.html, test/spec/controllers/landing.spec.js
This is the front-end work for creating a predefined Campus question. This is a typeahead question, searching Infobase for the campus names. See https://github.com/CruGlobal/ert-api/pull/731 for the back-end work.
=> EVENT-265 - Create campus question

app/scripts/directives/blockEditor.js, app/scripts/directives/questionToolbar.js, app/views/components/blockEditor.html, app/views/components/blockRegistration.html
This creates a predefined dormitory question and relies upon back-end changes in https://github.com/CruGlobal/ert-api/pull/732
=> EVENT-534 - Create predefined dormitory question

app/scripts/controllers/eventRegistrations.js, app/scripts/directives/showAnswer.js
https://secure.helpscout.net/conversation/508481926/190501/?folderId=610613
I probably killed this with a lodash upgrade at some point. Guess that's why tests are nice.
=> Fix lodash pick with functions

app/scripts/controllers/eventForm.js
https://secure.helpscout.net/conversation/512872949/191945/
=> Fix lodash uniq call

app/scripts/app.config.js, package.json, yarn.lock
Reverts CruGlobal/conf-registration-web#575
=> Revert "EVENT-544: Add cookie domain to share session cookies between www and…"

app/scripts/app.config.js, app/scripts/app_enforceAuth.js, app/scripts/controllers/eventDetails.js, app/scripts/controllers/registration.js, app/scripts/services/RegistrationCache.js, app/scripts/services/loginDialog.js, app/scripts/services/unauthorizedInterceptor.js, app/views/eventDetails/regOptions.html, app/views/eventDetails/regTypes.html, app/views/modals/loginDialog.html, test/spec/controllers/eventDetails.spec.js, test/spec/services/RegistrationCache.spec.js
=> EVENT-556 Option to not allow facebook login

app/views/modals/manualRegistration.html
The data structure for saving the form data could probably be refactored but this seems to work. I tested a little bit but not extensively.
=> Fix changing type in admin Add Registrant modal

app/index.ejs, app/scripts/services/validateRegistrant.js
Looks like prettier did not format this file the first time. My changes starts on line 283 and end on line 289.
=> Added link to React Dev Env

app/index.ejs
Prettier reformatted the file. But you can review it ignoring whitespace changes. I also merged it into staging.
https://secure.helpscout.net/conversation/888002030/336283/?folderId=610613
=> Use Adobe Launch on staging

app/views/eventDetails/eventInformation.html
as per request in https://secure.helpscout.net/conversation/949004975/362073
As supported by http://joda-time.sourceforge.net/timezones.html and https://github.com/CruGlobal/ert-api/blob/master/src/main/java/org/cru/crs/jaxrs/DateTimeZoneDeserializer.java#L17
=> Add africa timezones

app/views/components/adminNav.html
Reverts CruGlobal/conf-registration-web#653
=> EVENT-642: Restore "Payments" option in "More" menu

app/scripts/controllers/eventDetails.js, app/views/eventDetails/eventInformation.html, test/spec/controllers/eventDetails.spec.js
This PR attempts to eliminate `Transaction Rolled Back` errors, as documented in https://jira.cru.org/browse/EVENT-655.
=> EVENT-637: For Cru events: Require ministry and event type

app/scripts/filters/localizedCurrency.js
This is related to https://secure.helpscout.net/conversation/1049848711.
=> LocalizedCurrencyFilter_Fix

app/scripts/controllers/eventDetails.js, app/scripts/filters/localizedCurrency.js, test/spec/controllers/eventDetails.spec.js
Reverts CruGlobal/conf-registration-web#662 Turns out it wasn't that, the user was using safari and switched to chrome and everything worked.
=> Revert "LocalizedCurrencyFilter_Fix"

app/views/eventDetails/paymentOptions.html
https://jira.cru.org/browse/EVENT-660
=> EVENT-660-new Blurb for International Currency Selection

.travis.yml, test/spec/controllers/eventDetails.spec.js, test/spec/controllers/eventRegistrations.spec.js, test/spec/controllers/landing.spec.js, test/spec/controllers/paymentModal.spec.js, test/spec/controllers/paymentReport.spec.js, test/spec/controllers/registrationModal.spec.js, test/spec/controllers/reviewRegistration.spec.js, test/spec/directives/registrationTypeSelectVisibleTypes.spec.js, test/spec/filters/localizedCurrency.spec.js, test/spec/services/ConfCache.spec.js, test/spec/services/DateRangeService.spec.js, test/spec/services/logout.spec.js, test/spec/services/validateRegistrant.spec.js
Fix lint issues and add lint to travis build. I made this as a suggestion by @wrandall22 .
=> Add-Lint-To-Travis-Build

app/index.ejs
We'll merge this during upcoming ert-api outage for transition to AWS RDS, then revert afterwards.
=> Configure for maintenance mode.

app/index.ejs
Reverts CruGlobal/conf-registration-web#693
=> Revert "Configure for maintenance mode."

app/scripts/app_enforceAuth.js, app/scripts/controllers/eventDetails.js, app/scripts/services/analytics.service.js, app/scripts/services/loginDialog.js, app/scripts/services/logout.js, app/views/eventDetails/regOptions.html, app/views/eventDetails/regTypes.html, app/views/modals/loginDialog.html, test/spec/services/logout.spec.js, test/spec/testRegistrantTypeData.spec.js
Remove Instagram Login https://jira.cru.org/browse/EVENT-707
Instagram was to be retired as per “The final Instagram Legacy API permission (“Basic”) will be disabled on March 31, 2020"
See https://jira.cru.org/browse/EVENT-684
=> Remove Instragram Login

app/index.ejs
I figured we could add a placeholder description until Mike Schmitt gets back with me. Some sort of placeholder is better than JavaScript code. If you have a better suggestion for wording please let me know and I'll change it.
=> Add-Meta-Description

app/index.ejs, app/scripts/controllers/landing.js, app/scripts/controllers/reviewRegistration.js, app/scripts/services/analytics.service.js
[Jira](https://jira.cru.org/browse/EVENT-726)
=> EVENT-726: Add Google Tag Manager (GTM)

.travis.yml
Removed the env vars from the yml file in favor of setting the new rotated credentials in the Travis CI Web UI.
=> Rotate-secrets-available-to-CI

app/scripts/components/FormStatusModal/FormStatusModal.tsx
There wasn't much in regards to feedback when interacting with the form status modal. This PR adds a simple alert letting the user know that the status was successfully updated or that the form was successfully resent.
=> Add-Alert-Logic-FormStatusModal

webpack.config.js
Forgot to update the prod variable in the webpack config to not use ```TRAVIS_BRANCH```.
=> Fix-Webpack-Config-GHA

app/scripts/controllers/registration.js, app/scripts/controllers/reviewRegistration.js, app/views/registration.html
Fix based on comments in https://jira.cru.org/browse/EVENT-785. My original logic didn't really account for group registration. Having gone through fixing this, this must have been broken since group registrations were introduced.
=> EVENT-785-Hot-Fix

app/scripts/controllers/eventDetails.js, app/views/eventDetails/eventInformation.html
Requested that description has a tooltip that indicates the input supports HTML. Just utilized the same popup we use in other places that support HTML.
=> Add-ToolTip-Event-Description-Input

app/scripts/components/ExportModal/ExportModal.tsx
There have been a number of reports of issues related to registration exports recently. This is due to the rework of how the API produces the exports for registrations. For now, I'm reverting the work that will be affected by the API reverting its changes that introduced the issue/bug.
=> Registration-Export-Hot-Fix

app/scripts/app.module.js, app/scripts/controllers/eventDetails.js, app/scripts/controllers/eventOverview.js, app/scripts/controllers/registration.js, app/scripts/controllers/reviewRegistration.js, app/scripts/directives/blockEditor.js, app/scripts/directives/blockRegistration.js, app/scripts/directives/payment.js, app/scripts/filters/eventAddressFormat.js, app/scripts/main.js, app/scripts/services/ConfCache.js, app/scripts/services/validateRegistrant.js, app/views/blocks/addressQuestion.html, app/views/components/answerDisplay.html, app/views/eventDetails/eventInformation.html, app/views/eventOverview.html, app/views/paymentMethods/creditCard.html, app/views/registration.html, app/views/reviewRegistration.html, package.json, test/spec/filters/eventAddressFormat.spec.js, test/spec/services/validateRegistrant.spec.js, test/spec/testData.spec.js, yarn.lock
This reverts the revert of #803 and fixes the bug which caused us to revert.
=> EVENT-776 - Foreign Addresses

app/scripts/components/ExportModal/ExportModal.tsx
This includes both the revert mentioned by Christian as well as a fix needed to send block ids to the API, mentioned by Ben.
[Jira](https://jira.cru.org/browse/EVENT-778)
=> EVENT-778 - Fix export issue

.gitignore, app/styles/common.scss, app/views/eventDetails/promotions.html, languages/ert.pot, package.json
[Jira](https://jira.cru.org/browse/EVENT-798) and associated https://github.com/CruGlobal/ert-api/pull/994.
This PR adds chartfield text fields to the promotions area.
=> EVENT-798 - Add chartfield to promotions

app/views/eventDetails/eventInformation.html, app/views/eventDetails/regOptions.html
[Helpscout](https://secure.helpscout.net/conversation/2015685455/822110/)
Update spelling of Kathmandu
=> HS-822110 - Fix Nepal

app/scripts/directives/blocks.js, app/views/blocks/radioQuestion.html, app/views/modals/editRegistration.html, test/spec/directives/block.spec.js
Reported in [HelpScout #854613](https://secure.helpscout.net/conversation/2086060717).
**Summary of changes:**
* Getting the logic right for the answer value with two-way data binding based on two sources of data is extremely tricky, if not impossible, so I refactored it to use two separate variables. The first tracks the selected answer and the second tracks the text of the other input. Those two variables are then combined to produce the answer value.
* Validation in the edit registration modal is now performed in the same way as in the add registration modal.
=> Fix inconsistencies with other radio option

app/scripts/app.config.js, app/scripts/controllers/editRegistrationModal.js, app/scripts/controllers/registration.js, app/scripts/directives/showErrors.js, app/scripts/main.js, app/scripts/services/validationInterceptor.js, app/views/blocks/emailQuestion.html, app/views/eventDetails.html, app/views/eventDetails/contactInfo.html, app/views/eventPermissions.html, app/views/modals/editRegistration.html, app/views/modals/manualRegistration.html, test/spec/controllers/registration.spec.js, test/spec/services/validationInterceptor.spec.js
Implement client-side email address validation and show server-side validation errors.
=> Add client-side email address validation

app/scripts/directives/payment.js, app/scripts/services/payment.js, package.json, yarn.lock
I am updating the NPM package `cru-payments` to the new updated security patched version `@CruGlobal/cru-payments`.
- Removed old package `cru-payments`
- Added new package `@CruGlobal/cru-payments`
- Configured new package.
- **Added logs while testing on staging. Will remove it before deployment.**
=> Updating cru payments

app/scripts/controllers/registration.js, app/scripts/directives/datepicker.js, test/spec/directives/datepicker.spec.js
This commit causes all event details to an error on a date field when the user ties to save.
This reverts commit 0db31d84fb88f83057af1544067c3fafb22d046b.
=> Revert "Fix Graduation date question and saving questions validation (#842)"

.github/workflows/update-staging.yml
Adding the "On Staging" GitHub action. I copied this from MPDX and replaced `main` with `master`.
=> [no-Jira] Make on staging label work

app/scripts/services/error.js
Log network errors in Rollbar to assist with debugging https://secure.helpscout.net/conversation/2560557180/1132003?viewId=320673
=> [HS-1132003] Log network errors in Rollbar

app/scripts/directives/blocks.js, test/spec/directives/block.spec.js
Fixup to #854 to allow admins to edit registrants' name and email.
https://jira.cru.org/browse/EVENT-845
=> [EVENT-845] Allow admins to edit profile fields

app/scripts/controllers/eventOverview.js, test/spec/controllers/eventOverview.spec.js
- Updates conference registration count in eventOverview for hydration. Users would have to reload the page previously.
=> Resolve hydration issue for eventOverview
