CruGlobal/conf-registration-web

app/scripts/app.js
Use `replace()` to remove the auth routes from browser history. This allows the user to go back to the page they were at before the auth request. Currently if the user hits the back button after signing in, they go back to the auth route which then redirects them to the page they were already at. They aren't allowed to go back any further in the history.
A use case would be that a user searches for a conference and realizes it is the wrong conference and wants to go back and search for a different one.
I believe this only works if there wasn't a sign in involved (ie. conference didn't require user to be logged in). I realized that this is less useful if you can't get back past the Relay/FB sign in. It is hard to test because I get redirected away from localhost to stage so much. Let me …
=> Remove auth routes from history

app/scripts/directives/block.js
I noticed this while going through the modals and cleaning up styling for the responsive branch. If choice.amount is undefined or 0 (not '0'), this function throws an error about not being able to call replace on undefined and doesn't allow the user to save and close the modal. @adammeyer can you review?
=> Fix error on saving editBlockOptionAdvanced modal

app/index.html, app/scripts/directives/blockEditor.js, app/scripts/directives/showErrors.js, app/scripts/directives/stringToNumber.js, app/scripts/services/validateRegistrant.js, app/views/blocks/numberQuestion.html, app/views/components/blockEditor.html
This PR replaces https://github.com/CruGlobal/conf-registration-web/pull/497
- Add min and max inputs to Advanced tab of block editor
- Validate number input in rules section but allow invalid so updates to the number validation range don't cause api errors. The user can update it later.
- Add stringToNumber directive and casting to blockVisibleRuleCheck since rules are stored as strings
@jayakrishnanv What do you think of this? I was trying to make sure it worked and show you an example but I just ended up implementing it all. I started with your code but got rid of all the custom validation and DOM manipulation. The validation wasn't too bad but I spent a while trying to fix the rules so they would compare numbers as numbers instead of strings which I assume is a long standing bug. Let …
=> EVENT-379: Enable min/max validation on numberQuestion. Fix numberQuestion rules

bower.json
Update the `moment-timezone` dependency to remove deprecation warnings about `moment().zone`.
=> Update moment-timezone dependency

app/scripts/app.js, app/scripts/services/payment.js, app/views/eventDetails/paymentOptions.html
Instead of hard-coding the device ID on the client, the server now hard-codes the device ID and sends it to the client along with the TSYS manifest.
=> Use device ID from server

app/index.html, app/scripts/clientSideRedirection.js
Ensure that in staging and production, the SPA is running on an SSL-secured page and that it is not running on the raw `eventregistrationtool.com` domain because our SSL certificate is not valid for that domain.
=> Disallow pages on HTTP or not on a subdomain

app/index.html
Make sure that `clientSideRedirection.js` gets built into the `eventApp.js` bundle. Fixes bugs introduced in #531.
=> Correctly build clientSideRedirection.js

app/scripts/controllers/eventDetails.js, app/views/eventDetails/paymentOptions.html
This clarity is provided in order that conference administrators not attempt to add a merchant id as Authorize.NET credentials.
=> Explicitly name Authorize.NET on Payment Options page

app/scripts/controllers/eventDetails.js, app/scripts/services/ConfCache.js, app/views/eventDetails/paymentOptions.html
When saving a conference without a payment gateway type set, only set the type to TSYS if a payment gateway id is set.
=> Stop saving invalid payment gateways

app/scripts/services/payment.js
We discovered with the new give site that `toPromise` falls back to the browser's native promise implementation which doesn't exist in IE.
=> Specify $q as Promise implementation for rxjs toPromise

app/scripts/controllers/eventDetails.js
@dougworner Can you review this? You can reproduce this by going to the event details page, changing something, and then clicking a link to go to another page. It was redirecting to the home page instead of the desired page.
I saw this solution https://stackoverflow.com/a/31061068/665224
=> Fix discard changes redirect on leaving event details page

app/views/modals/choiceOptions.html, languages/ert.pot
Due to recent changes with FSG, the example of "t-shirt" is no longer acceptable.
=> Update additional cost language

app/views/modals/paymentsModal.html
This is required as PCI Compliance regulations do not allow entering of credit card numbers directly into applications (i.e. ERT) on devices not owned by the credit card holder.
=> Remove option for admin to submit credit card payment.

app/scripts/controllers/angularUiTreeConfig.js
For profile questions, they should default to checked for being saved to the profile. I dug in and found that the `defaultProfile` value was not being passed in when dropping a new question onto the form, and thus, every question defaulted to not being a profile question.
=> EVENT-532 - Default to Profile Question Checked

app/scripts/services/unauthorizedInterceptor.js, app/views/modals/loginDialog.html
- Remove link to eventDashboard when unauthorized. Navigating there doesn't make sense if you aren't logged in and the user can end up in a loop. Prevents `intendedRoute` from being changed.
- Re-auth if cookie expires for NONE auth type. Prevents anonymous users from being forced to login with loginDialog
I'm trying to make it better for the people dealing with session expiration in https://secure.helpscout.net/conversation/550303594/206163/. I'm not quite sure what they are encountering but it sounds like session expiration. Hopefully these help. Let me know if you see any issues that might come up with making these changes or if I made any bad assumptions.
=> Improve NONE auth provider type expiration

app/scripts/app.config.js
- Delete cookies on error and redirect to intended route
There is a potential the user could end up in a login loop if the intended route keeps taking them back to where they were that needed to login. But I think this strategy is better than just leaving them at a blank page. Let me know if you guys can think of any other strategies/improvements.
We still have the issue of the intendedRoute being set on both eventregistrationtool.com and www.eventregistrationtool.com and it reading the wrong one once login redirects to www. @adammeyer do you have any suggestions of how to solve that? My cookie PR failed... I could add back the [client side redirect to www](https://github.com/CruGlobal/conf-registration-web/pull/541/files#diff-a23f310732a5bb12ce55e68685d2df99) or make another S3 bucket to …
=> MHP-544: Add error handling to auth route's profile request

.gitignore, app/views/eventDetails/regOptions.html, app/views/eventDetails/regTypes.html, app/views/reviewRegistration.html, languages/ert.pot
Change the word 'Family' to 'Group' on the UI.
This shows up in multiple places including on the Registrant Types page. It affects the tooltips as well on that page.
See https://jira.cru.org/browse/EVENT-550
=> EVENT-550 Change the word 'Family' to 'Group' on the UI.

package.json, yarn.lock
Seems like old versions of `node-sass` never want to build with my version of Node or MacOS.
=> Upgrade node-sass

app/scripts/controllers/paymentModal.js, app/scripts/directives/payment.js, test/spec/controllers/paymentModal.spec.js
1) Do not require check number if status is not 'RECEIVED'
1) Require check number on update payment if status is 'RECEIVED' (it is always set 'RECEIVED' on update)
See https://jira.cru.org/browse/EVENT-654 (subtask of https://jira.cru.org/browse/EVENT-642)
=> EVENT-654: Fixes for check number for check payments

app/scripts/controllers/eventDetails.js, app/scripts/filters/localizedCurrency.js, test/spec/controllers/eventDetails.spec.js
This is another fix for that same help scout ticket. Basically it seems some conferences didn't have their currencyCode set to the default 'USD' by the API. Lee is eventually going to make a check that will set it no matter what API Side, but for now to help the user we are doing it client side.
=> LocalizedCurrencyFilter_Fix

app/scripts/filters/localizedCurrency.js
It seems some versions of safari are returning an array with an object `{type: 'nan", value: 'NaN'}` even though the correct values are being passed in. This just checks to see if any of those value exist in the array and then filters them out. Let me know if there is a cleaner way to do this.
=> FormatToParts-Fix 

app/scripts/services/loginDialog.js, app/views/modals/loginDialog.html
This works great for Relay 🎉  Thanks! It'll be much nicer to test PRs. You can test going through auth with the Netlify deploy status check below.
It doesn't seem to work for Facebook or Instagram 😞  Idk if that was intentional. They are hitting `auth/<provider>/authorization` unlike Relay which is hitting `auth/relay/login` if you missed applying this to that endpoint.
=> Pass clientUrl to API during sign in to be redirected back after

app/scripts/controllers/eventRegistrations.js, app/views/eventRegistrations.html, test/spec/controllers/eventRegistrations.spec.js, test/spec/testData.spec.js
Note that this PR removes ability to order registration (registrant) by column `last_updated_timestamp` (here https://github.com/CruGlobal/conf-registration-web/pull/682/files#diff-d3e6e77ecaa193aab05dae909c31f0d6L394) since supporting this requires substantive front end changes, which were deemed not necessary at time of this release.
=> EVENT-659: Date/Time stamp for ERT updates to a registration: answers and payments dates

package.json, yarn.lock
- Moving all versions to 3.5.0 breaks angular-wysiwyg
=> Fix yarn.lock after jQuery upgrade

app/index.ejs
I noticed there was some warnings in the admin menu on Facebook developers saying we should add these. So I went ahead and did so.
=> add-additional-meta-properties

app/views/components/blockEditor.html, app/views/eventDetails/eventInformation.html, app/views/eventDetails/paymentOptions.html, app/views/eventDetails/promotions.html, app/views/eventDetails/regOptions.html, app/views/eventDetails/regTypes.html, app/views/eventRegistrations.html, app/views/modals/choiceOptions.html
A small bug I noticed while working on the new journal upload page and adding a popover there. Checked the [docs](https://angular-ui.github.io/bootstrap/) to confirm the correct value. The popover technically still worked, the user just had to click on it instead of hovering over it. Not sure if it used to be ```mouseenter``` and there was a change along the way or something.
=> Fix-uib-popover-trigger

app/scripts/controllers/reviewRegistration.js, app/views/reviewRegistration.html
So with the addition of DocuSign, it has extended the confirmation time when submitting a registration. We believe that this extended wait time, along with no indicator of anything happening has made users impatient while they wait for the registration to submit. Possibly causing them to spam click the confirm button. Lee discovered that there's a small window between once the registration is complete and when the user is navigated to the confirmation page that the confirm button becomes enabled again and the user can press it. This will create a duplicate credit card transaction if pressed, causing the user to be charged twice. Lee and I both reproduced this on staging several times with ease. The solution was to leave the button disabled(unless there's an error with submitting), as they …
=> Fix-Duplicate-Credit-Card-Transaction-Issue

app/scripts/services/registration.js
@Benjamin-deVries Made a change to the API to return a specific error message when a user is registering and submits an invalid email. However, the frontend was not displaying this message and instead was using the default message set here: https://github.com/CruGlobal/conf-registration-web/blob/2bcc18f26066c2110ef99d5371411a54fb6ee023/app/scripts/services/registration.js#L52-L54
This change makes sure that the correlated logic for displaying error messages looks at the correct response object that is expected. https://github.com/CruGlobal/conf-registration-web/blob/2bcc18f26066c2110ef99d5371411a54fb6ee023/app/scripts/services/error.js#L9
I think there's a deeper issue here though that I will need to investigate and fix in a separate pr. We are noticing an increase in invalid emails and I …
=> Fix-Registration-Error-Messages-From-API

app/scripts/controllers/eventDetails.js
Ticket: https://jira.cru.org/browse/EVENT-786
Basically the ```refreshAllowedRegistrantTypes``` was happening before the GET, so then the ```$scope.conference``` was getting overridden by the ```response.data``` which isn't correctly formatted as needed.
=> EVENT-786-Associated-Registration-Types-Disappear

app/scripts/controllers/registration.js, app/scripts/directives/registrationTypeSelect.js, app/views/registration.html
Ticket: https://jira.cru.org/browse/EVENT-785
Basically, two bugs were happening and this fix resolves them both. If the first page is empty, as in no questions, when the user started registering they would land on that first page and it would be empty. The second has a similar end result of an empty page, but was resulted because there were no questions on the first page for the specific ```registrantType```. The ticket shows this in more detail.
So my fix was to filter out all pages that have no questions blocks. This was happening in some capacity already, but the links navigated to the first page, regardless of if it had any valid question blocks or if it was ```visible```.
=> EVENT-785-First-Page-Visible-When-No-Content-Applies

app/views/eventOverview.html, app/views/landing.html, app/views/modals/accessEvent.html, app/views/registration.html, app/views/reviewRegistration.html
After talking with some of the people from the ERT team, I recommended it would be better for safety reasons to not use ```toTrustedHTML```. They do lose the ability to use CSS, but the security benefits we gain outway that utility I believe.
Security reasons behind this are the fact that ```$sce.trustAsHtml``` overrides the ```ngSanitize``` that should normally happen. This means whatever is inputted, is not checked for anything that could be 'unsafe'. The sanitize logic essentially strips out everything that is not basic HTML code, including css, scripts, etc. 
With overriding the sanitize logic, I can do the following:
and since it's not scrubbed out, it gets executed
=> EVENT-781-Improvement

app/scripts/controllers/registration.js, test/spec/controllers/registration.spec.js
Interesting bug, basically a page now only renders if it has valid questions based on registrant type after my rework. But the question and answer rules also affect this. If an answer to a question causes another question to be visible on another page and the page wasn't valid before, AND that page is the next page, it basically would be skipped if you pressed 'Next Page'. But now we are continually checking valid pages as they navigate to the next page. I don't think this is needed for navigating back as rules shouldn't apply to previous pages.
=> Fix-Skip-Next-Page-Bug

app/scripts/components/ExportModal/ExportModal.tsx
The endpoint accepts `includeWithdrawn` not `includedWithdrawn` as a query parameter.
[Helpscout ticket](https://secure.helpscout.net/conversation/1872200440/757382)
=> HS-757382 - Fix typo

app/scripts/components/ExportModal/ExportModal.tsx
[Helpscout](https://secure.helpscout.net/conversation/1899342115/768912/)
When we fixed an issue in #807 to use the correct query parameters, we caused a new issue where we send the correct query parameters twice in the case of a filter being applied. Instead of overriding the `includeWithdrawn` and `includeIncomplete`, we were using both values: the ones from the checkboxes on the modal and the ones from the applied filtering.
This PR uses one value for each based on whether or not the filtering is applied.
=> HS-768912 - Only set includeWithdrawn and includeIncomplete once

app/scripts/directives/blocks.js, app/views/blocks/radioQuestion.html, test/spec/directives/block.spec.js
For some reason, `ng-model-options="{ debounce: 1000 }"` doesn't play nicely with radio buttons. If you click one option then a different one within one second, the selection is cleared when the debounce finally updates the value, even though the modal value is still set. Someone had a similar issue [here](https://stackoverflow.com/questions/31254291/angularjs-debounce-is-clearing-my-radio-input) with no resolution besides using a different method for debouncing.
Work around this issue by manually performing the debouncing within the controller.
=> Debounce option changes

app/scripts/directives/readFile.js, test/spec/directives/readFile.spec.js
Fixes this Rollbar exception caused by `files` being an empty array: https://rollbar.com/Cru/ert-web/items/601/occurrences/307996597668/
=> Fix file is undefined exception

app/scripts/services/loginDialog.js, app/scripts/services/modalMessage.js
Previously, when the client's auth token expired, the UI would show the login modal _and_ an "Invalid authorization code" modal when navigating to a registration page. This is because `unauthorizedInterceptor` was noticing the 401 response for the `/conferences/:id/registrations/current` request and showing the login modal, and these lines were also showing a modal for the error:
https://github.com/CruGlobal/conf-registration-web/blob/5bfe23ffc2b074cacc1162e801c96ca854b461a0/app/scripts/app.config.js#L124
https://github.com/CruGlobal/conf-registration-web/blob/5bfe23ffc2b074cacc1162e801c96ca854b461a0/app/scripts/controllers/registration.js#L22-L24
My changes suppress other modals when the login modal is open.
https://jira.cru.org/browse/EVENT-811
=> [EVENT-811] Suppress modals when login modal is open

app/scripts/components/RegistrationFilters/RegistrationFilters.test.tsx, app/scripts/components/RegistrationFilters/RegistrationFilters.tsx
We are occasionally running into timeouts when uploading 100 transactions. Temporarily prevent these errors by making 50 the most transactions that can be viewed at one time. This will be reverted in the future when we have time for a better solution, like implementing batching on the server.
https://secure.helpscout.net/conversation/2211009504/924915/
Tested in staging ✅
=> [no-Jira] Remove 100 item page option

app/scripts/directives/showErrors.js
Fix `Multiple directives [pickADate, showErrors (module: confRegistrationWebApp)] asking for new/isolated scope on: <pick-a-date>` error introduced in 192aaa30cd1c95ca990c815cccb36c19f55c0ab7.
Solution: revert the `show-errors` directive back to no longer creating a new isolated scope and instead using `$scope.$eval` to determine the value of the `show-errors-instant` attribute.
https://secure.helpscout.net/conversation/2245104032/946275?folderId=7599852
=> [HS-946275] Fix multiple Angular directives error

app/scripts/controllers/eventDetails.js, app/views/blocks/addressQuestion.html, app/views/blocks/checkboxQuestion.html, app/views/blocks/genderQuestion.html, app/views/blocks/nameQuestion.html, app/views/blocks/numberQuestion.html, app/views/blocks/yearInSchoolQuestion.html, app/views/eventDetails/eventInformation.html, test/spec/controllers/eventDetails.spec.js, test/spec/mockHttpBackend.spec.js, test/spec/testData.spec.js, test/spec/testRegistrantTypeData.spec.js, types/conference.ts
https://jira.cru.org/browse/EVENT-821
On the Details tab of an event ERT we need to be able to collect the event type in order to capture the participant journey and know the event journey the Cru participant has followed during their time with Cru.  While the list is Campus specific the same process could be used for other ministries based on the participant event journey they with to follow.
When an admin answers "Yes" this is a Cru event we can use the "Ministry Hosting Event" dropdown to determine what event types would be needed. 
In this case if the Ministry Hosting the event as “Campus - Field Team/Strategy” or “Campus - National Team/Strategy” and I would also suggest that when the Ministry Purpose is selected as “Ministry Conference/Event” or "Ministry Mission Trip".  The …
=> EVENT-821 Add Event Type dropdown menu

app/scripts/controllers/eventDetails.js
* A recent deployment broke some code on the event details page, resulting in the Associated Registrant Types no longer showing. This fix adds back the code which was removed.
* Had to remove unwanted properties from the conference copied object, which is being sent to the API. properties were causing errors.
*  I added this fix a few days ago but part of it was removed from Prod when it was merged. The code which was removed didn't show on the PR as edited files, which is why we didn't catch it.
=> Correction Associated Registrant Types after merge

app/scripts/directives/datepicker.js, app/views/components/answerDisplay.html, test/spec/directives/datepicker.spec.js
The Graduation date question displays the entire date/timestamp from the API when looking at past registrations. When displaying the dates, format them to make them more readable.
- Removed logic around formatting the initial date when loading a date picker. The full date/timestamp is fine. Each datepicker formats the displayed date based on what kind of question it is.
- Formatted the dates in a readable format when they are displayed throughout the ERT.
- Added new tests to check the initialDate
=> Date format fix

app/styles/user-registration.scss
A user complained that the banner was making the event page not responsive. - https://secure.helpscout.net/conversation/2389694143/1033842?folderId=7599856
- Added CSS `min()` function to determine which is smaller, 100% of container width or 582px.
=> Event banner oversized on mobile devices 

app/.htaccess, app/scripts/components/GoogleLogin/GoogleLogin.tsx
https://jira.cru.org/browse/EVENT-843
Google login is changing and we need to be ready for it, we should hop on the FedCM beta to make sure this move won't break ERT's ability to login via Google.
https://developers.googleblog.com/2023/08/announcing-federated-credential-management-beta-for-gis.html
I followed these steps: https://developers.google.com/identity/gsi/web/guides/fedcm-migration
=> EVENT-843 - FedCM Beta Testing

yarn.lock
It looks like yarn.lock and package.json got out of sync after #834. Every time I run `yarn install`, yarn makes these changes to the lockfile.
=> [no-Jira] Sync yarn.lock and package.json

app/scripts/controllers/eventForm.js, app/scripts/controllers/eventRegistrations.js, app/scripts/controllers/reviewRegistration.js, test/spec/controllers/eventForm.spec.js, test/spec/controllers/eventRegistrations.spec.js, test/spec/controllers/reviewRegistration.spec.js, test/spec/testData.spec.js
Increase the test coverage of some of the most frequently-modified files.
=> [no-Jira] Improve test coverage

app/scripts/errorNotify.js, package.json, yarn.lock
Upgrade rollbar to get additional telemetry such as network activity like `give-web` has. [Here's an example](https://app.rollbar.com/a/Cru/fix/item/ert-web/795/occurrence/402828749624#detail) of an occurrence in staging. Please double-check that all PII is removed.
Assisting with debugging https://secure.helpscout.net/conversation/2560557180/1132003?viewId=320673
=> [HS-1132003] Upgrade rollbar

app/scripts/directives/blocks.js, app/views/blocks/emailQuestion.html, app/views/blocks/nameQuestion.html, test/spec/directives/block.spec.js
Prevent staff from editing name and email profile fields. These fields are prepopulated and should not be modified.
If you need a conference to test with, you're welcome to use this one: https://stage.eventregistrationtool.com/eventDetails/ec6ac5f9-1df0-4b69-b09d-f85ce39001ef. It is configured to allow Okta and Google logins.
https://jira.cru.org/browse/EVENT-845
=> [EVENT-845] Disable editing staff profile info

app/scripts/directives/blocks.js, test/spec/directives/block.spec.js
https://secure.helpscout.net/conversation/2613153780/1165153?folderId=7669074
1) First Name / Last Name
I noticed that within the Name fields the following:
{{'First Name' | translate}}
2) Name Tag Name Missing
For current ERT's, and ERT's I am cloning, where I once had a Name Tag Name option, I am seeing the question there, but I am noticing the response field missing.
I was not able to replicate these issues. But on this particular event, there is a typescript errors saying `Cannot read properties of undefined (reading 'primaryRegistrantId')`
=> HelpScout1165153 Name Field issue

app/scripts/controllers/editRegistrationModal.js, app/views/blocks/emailQuestion.html, app/views/modals/editRegistration.html
We received a [HelpScout ticket](https://secure.helpscout.net/conversation/2684171191/1211838/) from an admin wanting to change the registration type on incomplete registrations. Because some required fields hadn't been filled out yet, the edit registration modal wasn't letting admins save the registration. To resolve that, this PR removes the `ng-disabled` check and lets admins always update registrations. Note that unlike `Save`, `Save & Set as Completed` still requires all questions to have valid questions.
I also had to set `allowInvalid` on `ng-model-options` for email address fields. Without it, data corruption is possible (see [screen capture](https://github.com/user-attachments/assets/5f7c0874-3ddb-4da6-b4fc-401229e16085)). To reproduce, create an incomplete registration, change …
=> [HS-1211838] Allow editing incomplete registrations

app/scripts/controllers/eventDashboard.js, app/scripts/controllers/eventDetails.js, app/views/modals/createEvent.html, test/spec/controllers/eventDetails.spec.js
* Prevent users from creating conferences with names containing ampersand or double quotes. Apparently, those special characters are causing issues on the server.
* Also prevent users from editing conferences to contain an ampersand or double quote. If they have an existing conference with an ampersand or a double quote, they will change the name before they can edit any other conference details. My understanding is that that is desirable.
* Also prevent users from editing conference abbreviations to contain an ampersand or double quote.
* From the admin dashboard, click "Create New Event"
* Validate that there are errors when the event name is empty (after focusing the name input and then moving focus) and the form cannot be submitted.
* Validate that there are errors when the event name …
=> [HS-1241612] Prevent conference names from containing special characters

app/views/reviewRegistration.html
Users are requesting that the promo code box is always visible instead of requiring the user to click the "Add Promotion Code" link first.
HelpScout ticket: https://secure.helpscout.net/conversation/2718660687/1234291/
[EVENT-849](https://jira.cru.org/browse/EVENT-849)
=> [EVENT-849] Always show promo code box

app/scripts/controllers/eventDetails.js, app/scripts/directives/blockEditor.js, app/styles/event-admin.scss, app/views/components/blockEditor.html, test/spec/controllers/eventDetails.spec.js
* Change the titles of auto-created liability questions to clarify that we are asking about the age of the participant (I assume this was causing confusion when parents would register for their children)
* Note that this will not change the titles of lability questions created before this change
* Make the titles of liability questions editable
* Create a new conference
* Check that the title of the liability question about age is "Are you (the participant) under 18 years old?"
* Check that the edit buttons for liability questions (age, guardian name, and guardian email) are not disabled
* Check that clicking the edit buttons for liability questions shows the title text input and changing it changes the question's title
Manually merged into `staging`
Requested in this ticket: …
=> [HS-1310779] Liability form wording changes

app/views/blocks/checkboxQuestion.html
Fix DOM nesting error introduced in #876 that prevented the "Force selection" checkbox from displaying.
HelpScout ticket: https://secure.helpscout.net/conversation/2879252870/1325929?viewId=320670
* Add a Checkbox question to the event
* Add an answer option
* Check the answer option you added
* Ensure that the Force selection checkbox is visible
=> [HS-1325929] Fix force selection checkbox being hidden

app/scripts/controllers/eventDetails.js, app/scripts/controllers/registrationModal.js, app/scripts/directives/registrationTypeSelect.js, app/views/components/blockEditor.html, app/views/components/registrationTypeSelect.html, app/views/eventDetails/regTypes.html, app/views/modals/addRegistrantType.html, app/views/reviewRegistration.html
- Front end now handles Couple-Spouse creation and association logic
- Readdition of the standalone Spouse type required more extensive filtering in multiple areas.
- I have a temporary solution for this but would like to rewrite to avoid duplicate filtering logic
=> Change front end to handle Couple-Spouse pairs, re-add Spouse type
